import type { InquilinoFormValues } from "@/shared/schemas/inquilino";
import type { Inquilino, InquilinoScoring } from "../types";

export const INQUILINO_FORM_DEFAULTS: InquilinoFormValues = {
  nombres: "",
  apellidos: "",
  tipo_documento: "dni",
  numero_documento: "",
  fecha_nacimiento: "",
  nacionalidad: "España",
  telefono: "",
  email: "",
  direccion_actual: "",
  ciudad: "",
  pais: "España",
  ocupacion: "",
  empresa: "",
  tipo_contrato_laboral: "indefinido",
  ingresos_mensuales: undefined,
  antiguedad_laboral: "",
  referencia_laboral: "",
  telefono_referencia_laboral: "",
  observaciones_financieras: "",
  propiedad_id: "",
  unidad_id: "",
  fecha_ingreso: "",
  fecha_salida: "",
  canon_mensual: undefined,
  deposito: undefined,
  responsable_servicios: "inquilino",
  ocupantes: 1,
  status: "candidato",
  referencias: {
    nombre_personal: "",
    telefono_personal: "",
    relacion: "",
    nombre_arrendador: "",
    telefono_arrendador: "",
    comentario: "",
  },
  scoring: {
    nivel: "sin_evaluar",
    documentacion_completa: false,
    ingresos_suficientes: false,
    historial_pagos: false,
    referencias_positivas: false,
    estabilidad_laboral: false,
    comportamiento_reportado: false,
    danos_previos: false,
    observaciones_gestor: "",
  },
};

export const DEFAULT_SCORING: InquilinoScoring = {
  nivel: "sin_evaluar",
  documentacion_completa: false,
  ingresos_suficientes: false,
  historial_pagos: false,
  referencias_positivas: false,
  estabilidad_laboral: false,
  comportamiento_reportado: false,
  danos_previos: false,
  actualizado_at: new Date().toISOString(),
};

export function inquilinoToFormValues(i: Inquilino): InquilinoFormValues {
  return {
    nombres: i.nombres,
    apellidos: i.apellidos,
    tipo_documento: i.tipo_documento,
    numero_documento: i.numero_documento,
    fecha_nacimiento: i.fecha_nacimiento ?? "",
    nacionalidad: i.nacionalidad ?? "",
    telefono: i.telefono,
    email: i.email,
    direccion_actual: i.direccion_actual ?? "",
    ciudad: i.ciudad ?? "",
    pais: i.pais ?? "",
    ocupacion: i.ocupacion ?? "",
    empresa: i.empresa ?? "",
    tipo_contrato_laboral: i.tipo_contrato_laboral,
    ingresos_mensuales: i.ingresos_mensuales,
    antiguedad_laboral: i.antiguedad_laboral ?? "",
    referencia_laboral: i.referencia_laboral ?? "",
    telefono_referencia_laboral: i.telefono_referencia_laboral ?? "",
    observaciones_financieras: i.observaciones_financieras ?? "",
    propiedad_id: i.asignacion?.propiedad_id ?? "",
    unidad_id: i.asignacion?.unidad_id ?? "",
    fecha_ingreso: i.asignacion?.fecha_ingreso ?? "",
    fecha_salida: i.asignacion?.fecha_salida ?? "",
    canon_mensual: i.asignacion?.canon_mensual,
    deposito: i.asignacion?.deposito,
    responsable_servicios: i.asignacion?.responsable_servicios ?? "inquilino",
    ocupantes: i.asignacion?.ocupantes ?? 1,
    status: i.status,
    referencias: i.referencias ?? INQUILINO_FORM_DEFAULTS.referencias,
    scoring: i.scoring ?? INQUILINO_FORM_DEFAULTS.scoring,
  };
}
