// Auto-generated by: pnpm db:types
// Do not edit manually. Run `pnpm db:types` to regenerate after schema changes.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          nombre: string | null;
          apellidos: string | null;
          rol: "propietario" | "gestor" | "inquilino";
          avatar_url: string | null;
          telefono: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      propiedades: {
        Row: {
          id: string;
          owner_id: string;
          titulo: string;
          descripcion: string | null;
          direccion: string;
          ciudad: string;
          codigo_postal: string;
          precio_mes: number;
          habitaciones: number;
          banos: number;
          metros_cuadrados: number | null;
          tipo_alquiler: "tradicional" | "habitaciones" | "corta_estancia" | "flipping";
          estado: "disponible" | "alquilada" | "mantenimiento" | "inactiva";
          lat: number | null;
          lng: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["propiedades"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["propiedades"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
